export default {
  blocks: {
    'article-block': { title: 'Article', icon: 'book-open' },
    'audio-block': { title: 'Audio', icon: 'audio' },
    'code-block': { title: 'Code', icon: 'code' },
    'divider-block': { title: 'Divider', icon: 'minus-line' },
    'document-block': { title: 'Document', icon: 'document' },
    'eme-form-block': { title: 'EME Form', icon: 'short-text' },
    'facebook-post-block': { title: 'Facebook Post', icon: 'facebook-circle' },
    'facebook-video-block': { title: 'Facebook Video', icon: 'facebook' },
    'gallery-block': { title: 'Gallery', icon: 'gallery' },
    'google-map-block': { title: 'Google Map', icon: 'google' },
    'heading-block': { title: 'Heading', icon: 'header' },
    'iframe-block': { title: 'IFrame', icon: 'iframe' },
    'image-block': { title: 'Image', icon: 'camera' },
    'imgur-post-block': { title: 'Imgur Post', icon: 'imgur' },
    'instagram-media-block': { title: 'Instagram Media', icon: 'instagram' },
    'page-break-block': { title: 'Page Break', icon: 'page-break' },
    'pinterest-pin-block': { title: 'Pinterest Pin', icon: 'pinterest' },
    'poll-block': { title: 'Poll', icon: 'poll' },
    'poll-grid-block': { title: 'Poll Grid', icon: 'poll-grid' },
    'quote-block': { title: 'Quote', icon: 'quote' },
    'soundcloud-audio-block': { title: 'SoundCloud Audio', icon: 'soundcloud' },
    'spotify-embed-block': { title: 'Spotify Embed', icon: 'spotify' },
    'spotify-track-block': { title: 'Spotify Track', icon: 'spotify' },
    'text-block': { title: 'Paragraph', icon: 'paragraph' },
    'tiktok-embed-block': { title: 'TikTok Embed', icon: 'tiktok' },
    'tumblr-post-block': { title: 'Tumblr Post', icon: 'tumblr' },
    'twitter-tweet-block': { title: 'Twitter Tweet', icon: 'x' },
    'video-block': { title: 'Video', icon: 'play-outline' },
    'vimeo-video-block': { title: 'Vimeo Video', icon: 'vimeo' },
    'youtube-playlist-block': { title: 'YouTube Playlist', icon: 'playlist' },
    'youtube-video-block': { title: 'YouTube Video', icon: 'youtube' },
  },
  selector: {
    blocks: [
      'article-block',
      'audio-block',
      'code-block',
      'divider-block',
      'document-block',
      'eme-form-block',
      'gallery-block',
      'heading-block',
      'iframe-block',
      'image-block',
      'page-break-block',
      'poll-block',
      'poll-grid-block',
      'quote-block',
      'text-block',
      'video-block',
    ],
    externalBlocks: [
      'facebook-post-block',
      'facebook-video-block',
      'google-map-block',
      'imgur-post-block',
      'instagram-media-block',
      'pinterest-pin-block',
      'soundcloud-audio-block',
      'spotify-embed-block',
      'tiktok-embed-block',
      'tumblr-post-block',
      'twitter-tweet-block',
      'vimeo-video-block',
      'youtube-playlist-block',
      'youtube-video-block',
    ]
  },
};
