export const PLUGIN_PREFIX = 'iam/';
const t = id => `${PLUGIN_PREFIX}${id}`;

export const serviceIds = {
  PREFIX: PLUGIN_PREFIX,

  AUTHORIZER: t('AUTHORIZER'),
  AUTH0_SESSION_KEY: t('AUTH0_SESSION_KEY'),
};

export const actionTypes = {
  PREFIX: PLUGIN_PREFIX,

  LOGIN_ACCEPTED: t('LOGIN_ACCEPTED'),
  LOGIN_REJECTED: t('LOGIN_REJECTED'),
  LOGOUT_COMPLETED: t('LOGOUT_COMPLETED'),

  USER_LOADED: t('USER_LOADED'),
};
