export default {
  DRAFTJS_BLOCK_KEY: 'DRAFTJS_BLOCK_KEY',
  DRAG_BUTTON_ID: 'button-drag-block',
  INSERT_BLOCK_MARKER_ID: 'insert-block-marker',

  DOUBLE_ENTER_ON_LIST: Symbol('DOUBLE_ENTER_ON_LIST'),
  POSITION_ABOVE: Symbol('POSITION_ABOVE'),
  POSITION_AFTER: Symbol('POSITION_AFTER'),
  POSITION_BEFORE: Symbol('POSITION_BEFORE'),
  POSITION_BELOW: Symbol('POSITION_BELOW'),
  SOFT_NEWLINE: Symbol('SOFT_NEWLINE'),
  BLOCKS_CUT: Symbol('BLOCKS_CUT'),
  BLOCKS_COPIED: Symbol('BLOCKS_COPIED'),
};
