export default {
  DOUBLE_ENTER_ON_LIST: 'DOUBLE_ENTER_ON_LIST',
  DRAFTJS_BLOCK_KEY: 'DRAFTJS_BLOCK_KEY',
  DRAG_BUTTON_ID: 'button-drag-block',
  INSERT_BLOCK_MARKER_ID: 'insert-block-marker',
  POSITION_ABOVE: 'POSITION_ABOVE',
  POSITION_AFTER: 'POSITION_AFTER',
  POSITION_BEFORE: 'POSITION_BEFORE',
  POSITION_BELOW: 'POSITION_BELOW',
  SOFT_NEWLINE: 'SOFT_NEWLINE',
};
