export default {
  DRAFTJS_BLOCK_KEY: 'DRAFTJS_BLOCK_KEY',
  DRAG_BUTTON_ID: 'button-drag-block',
  INSERT_BLOCK_MARKER_ID: 'insert-block-marker',
  POSITION_ABOVE: 'POSITION_ABOVE',
  POSITION_BELOW: 'POSITION_BELOW',

  ATOMIC_BLOCKS_COPIED: Symbol('ATOMIC_BLOCKS_COPIED'),
  ATOMIC_BLOCKS_CUT: Symbol('ATOMIC_BLOCKS_CUT'),
  DOUBLE_ENTER_ON_LIST: Symbol('DOUBLE_ENTER_ON_LIST'),
  POSITION_AFTER: Symbol('POSITION_AFTER'),
  POSITION_BEFORE: Symbol('POSITION_BEFORE'),
  SOFT_NEWLINE: Symbol('SOFT_NEWLINE'),
};
