import { handleDragEnd as handleDragEndFn, handleDragStart as handleDragStartFn } from '@triniti/cms/components/blocksmith-field/utils/handleDrag.js';
// import addEmojiFn from './addEmoji.js';
import areKeysSameFn from '@triniti/cms/components/blocksmith-field/utils/areKeysSame.js';
import attachImmutableEntitiesToEmojisFn from '@triniti/cms/components/blocksmith-field/utils/attachImmutableEntitiesToEmojis.js';
import blockParentNodeUtil from '@triniti/cms/components/blocksmith-field/utils/blockParentNode.js';
import convertToCanvasBlocksFn from '@triniti/cms/components/blocksmith-field/utils/convertToCanvasBlocks.js';
import convertToEditorStateFn from '@triniti/cms/components/blocksmith-field/utils/convertToEditorState.js';
// import copySelectedBlocksToClipboardFn from './copySelectedBlocksToClipboard.js';
// import createLinkAtSelectionFn from './createLinkAtSelection.js';
// import deleteBlockFn from './deleteBlock.js';
// import deleteSelectedBlocksFn from './deleteSelectedBlocks.js';
// import dropBlockFn from './dropBlock.js';
// import findBlockFn from './findBlock.js';
import getBlockForKeyFn from '@triniti/cms/components/blocksmith-field/utils/getBlockForKey.js';
// import getBlockNodeFn from './getBlockNode.js';
import getDraggedBlockNodeFn from '@triniti/cms/components/blocksmith-field/utils/getDraggedBlockNode.js';
import getInsertBlockMarkerNodeFn from '@triniti/cms/components/blocksmith-field/utils/getInsertBlockMarkerNode.js';
// import getListBlockNodesFn from './getListBlockNodes.js';
// import getListBlocksFn from './getListBlocks.js';
// import getValidBlockTargetFn from './getValidBlockTarget.js';
// import getWordCountFn from './getWordCount.js';
import handleDocumentDragoverFn from '@triniti/cms/components/blocksmith-field/utils/handleDocumentDragover.js';
import handleDocumentDropFn from '@triniti/cms/components/blocksmith-field/utils/handleDocumentDrop.js';
import hasEntityFn from '@triniti/cms/components/blocksmith-field/utils/hasEntity.js';
// import insertCanvasBlocksFn from './insertCanvasBlocks.js';
// import insertEmptyBlockFn from './insertEmptyBlock.js';
// import isAtomicBlockSelectedFn from './isAtomicBlockSelected.js';
import isBlockAListFn from '@triniti/cms/components/blocksmith-field/utils/isBlockAList.js';
import isBlockEmptyFn from '@triniti/cms/components/blocksmith-field/utils/isBlockEmpty.js';
// import isFirstListBlockFn from './isFirstListBlock.js';
// import isLastListBlockFn from './isLastListBlock.js';
// import loadFacebookSDKFn from './loadFacebookSDK.js';
// import loadTwitterSDKFn from './loadTwitterSDK.js';
import normalizeKeyFn from '@triniti/cms/components/blocksmith-field/utils/normalizeKey.js';
import preventDefaultFn from '@triniti/cms/components/blocksmith-field/utils/preventDefault.js';
// import pushEditorStateFn from './pushEditorState.js';
// import removeLinkAtSelectionFn from './removeLinkAtSelection.js';
// import replaceBlockAtKeyFn from './replaceBlockAtKey.js';
// import selectBlockFn, { selectionTypes } from './selectBlock.js';
// import selectionUtil from './selection.js';
// import shiftBlockFn from './shiftBlock.js';
// import sidebarUtil from './sidebar.js';
import styleBlockTargetNodeStatusFn from '@triniti/cms/components/blocksmith-field/utils/styleBlockTargetNodeStatus.js';
import styleDragTargetFn from '@triniti/cms/components/blocksmith-field/utils/styleDragTarget.js';
// import updateBlocksFn from './updateBlocks.js';
// import validateBlocksFn from './validateBlocks.js';

// export const addEmoji = addEmojiFn;
export const areKeysSame = areKeysSameFn;
export const attachImmutableEntitiesToEmojis = attachImmutableEntitiesToEmojisFn;
export const blockParentNode = blockParentNodeUtil;
export const convertToCanvasBlocks = convertToCanvasBlocksFn;
export const convertToEditorState = convertToEditorStateFn;
// export const copySelectedBlocksToClipboard = copySelectedBlocksToClipboardFn;
// export const createLinkAtSelection = createLinkAtSelectionFn;
// export const deleteBlock = deleteBlockFn;
// export const deleteSelectedBlocks = deleteSelectedBlocksFn;
// export const dropBlock = dropBlockFn;
// export const findBlock = findBlockFn;
export const getBlockForKey = getBlockForKeyFn;
// export const getBlockNode = getBlockNodeFn;
export const getDraggedBlockNode = getDraggedBlockNodeFn;
export const getInsertBlockMarkerNode = getInsertBlockMarkerNodeFn;
// export const getListBlockNodes = getListBlockNodesFn;
// export const getListBlocks = getListBlocksFn;
// export const getValidBlockTarget = getValidBlockTargetFn;
// export const getWordCount = getWordCountFn;
export const handleDocumentDragover = handleDocumentDragoverFn;
export const handleDocumentDrop = handleDocumentDropFn;
export const handleDragEnd = handleDragEndFn;
export const handleDragStart = handleDragStartFn;
export const hasEntity = hasEntityFn;
// export const insertCanvasBlocks = insertCanvasBlocksFn;
// export const insertEmptyBlock = insertEmptyBlockFn;
// export const isAtomicBlockSelected = isAtomicBlockSelectedFn;
export const isBlockAList = isBlockAListFn;
export const isBlockEmpty = isBlockEmptyFn;
// export const isFirstListBlock = isFirstListBlockFn;
// export const isLastListBlock = isLastListBlockFn;
// export const loadFacebookSDK = loadFacebookSDKFn;
// export const loadTwitterSDK = loadTwitterSDKFn;
export const normalizeKey = normalizeKeyFn;
export const preventDefault = preventDefaultFn;
// export const pushEditorState = pushEditorStateFn;
// export const removeLinkAtSelection = removeLinkAtSelectionFn;
// export const replaceBlockAtKey = replaceBlockAtKeyFn;
// export const selectBlock = selectBlockFn;
// export const selectBlockSelectionTypes = selectionTypes;
// export const selection = selectionUtil;
// export const shiftBlock = shiftBlockFn;
// export const sidebar = sidebarUtil;
export const styleBlockTargetNodeStatus = styleBlockTargetNodeStatusFn;
export const styleDragTarget = styleDragTargetFn;
// export const updateBlocks = updateBlocksFn;
// export const validateBlocks = validateBlocksFn;
