export const PLUGIN_PREFIX = '@triniti/dam/';

const t = (id) => `${PLUGIN_PREFIX}${id}`;

export const serviceIds = {
  PREFIX: PLUGIN_PREFIX,
  ASSET_SUBSCRIBER: t('asset_subscriber'),
  IMAGE_ASSET_SUBSCRIBER: t('image_asset_subscriber'),
};

export const routeIds = {
  PREFIX: PLUGIN_PREFIX,

  ASSET: t('asset'),
  SEARCH_ASSETS: t('search_assets'),

  INDEX: t('index'),
};

export const formNames = {
  UPLOADER_FORM_PREFIX: t('uploader-'),
  ASSET: t('asset'),
};

export const actionTypes = {
  PREFIX: PLUGIN_PREFIX,

  PATCH_ASSETS_REQUESTED: t('PATCH_ASSETS_REQUESTED'),
  DISPLAY_BATCH_EDIT_REQUESTED: t('DISPLAY_BATCH_EDIT_REQUESTED'),

  CLEAR_PROCESSED_FILES_REQUESTED: t('CLEAR_PROCESSED_FILES_REQUESTED'),
  FLUSH_PROCESSED_FILES_CHANNELS_REQUESTED: t('FLUSH_PROCESSED_FILES_CHANNELS_REQUESTED'),

  PROCESS_FILES_REQUESTED: t('PROCESS_FILES_REQUESTED'),
  PROCESS_FILE_COMPLETED: t('PROCESS_FILE_COMPLETED'),
  PROCESS_FILE_FAILED: t('PROCESS_FILE_FAILED'),
  PROCESS_FILE_RETRY_REQUESTED: t('PROCESS_FILE_RETRY_REQUESTED'),

  PROCESSED_FILE_ASSET_UPDATED: t('PROCESSED_FILE_ASSET_UPDATED'),
  PROCESSED_FILE_SELECTED: t('PROCESSED_FILE_SELECTED'),

  PROCEESS_VARIANT_REQUESTED: t('PROCEESS_VARIANT_REQUESTED'),

  UPLOAD_FILE_STARTED: t('UPLOAD_FILE_STARTED'),
  UPLOAD_FILE_FULFILLED: t('UPLOAD_FILE_FULFILLED'),
  UPLOAD_FILE_REJECTED: t('UPLOAD_FILE_REJECTED'),

  REMOVE_PROCESSED_FILE_REQUESTED: t('REMOVE_PROCESSED_FILE_REQUESTED'),

  CREATE_ASSET_REQUESTED: t('CREATE_ASSET_REQUESTED'),

  SEARCH_ASSETS_REQUESTED: t('SEARCH_ASSETS_REQUESTED'),

  LINK_ASSETS_REQUESTED: t('LINK_ASSETS_REQUESTED'),
  UNLINK_ASSETS_REQUESTED: t('UNLINK_ASSETS_REQUESTED'),

  REORDER_GALLERY_ASSETS_REQUESTED: t('REORDER_GALLERY_ASSETS_REQUESTED'),
  UPDATE_ASSETS_IN_UPLOADER_REQUESTED: t('UPDATE_ASSETS_IN_UPLOADER_REQUESTED'),
};

export const fileUploadStatuses = {
  COMPLETED: 'COMPLETED',
  ERROR: 'ERROR',
  PROCESSING: 'PROCESSING',
  UPLOADED: 'UPLOADED',
  UPLOADING: 'UPLOADING',
};

export const utilityTypes = {
  GALLERY_SEQUENCE_COUNTER: t('uploaderGallerySequence'),
};

export const DATE_FIELD_QUICK_SELECT_OPTIONS = [
  {
    amount: 5,
    unit: 'year',
  },
  {
    amount: 1,
    unit: 'year',
  },
];
